# Generated by Django 4.2.30 on 2026-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.TextField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], default='tenant'),
        ),
    ]
