# Generated by Django 4.2.30 on 2026-08-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.TextField(choices=[('tenant', 'Tenant / Seeker'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], default='tenant'),
        ),
    ]
