"""
listings/models.py

Mirrors the two public-schema tables from your Supabase backup:

  public.listing        → Listing
  public.listingimages  → ListingImage

Column mapping is 1-to-1. Supabase-specific notes:
  - id BIGINT GENERATED BY DEFAULT AS IDENTITY  → BigAutoField (Django default)
  - created_at TIMESTAMPTZ DEFAULT now()        → auto_now_add=True
  - "createdBy" FK → user_profiles(email)       → FK to UserProfile on email field
  - coordinates JSON                            → JSONField
  - lotSize / area / price / hoa REAL           → FloatField
  - builtIn / parking NUMERIC                   → DecimalField
"""

from django.db import models
from accounts.models import UserProfile


class Listing(models.Model):
    """
    Mirrors public.listing
    """

    PROPERTY_TYPE_CHOICES = [
    ("Single Family House", "Single Family House"),
    ("Town House", "Town House"),
    ("Condo", "Condo"),
    ("house", "House"),
    ("apartment", "Apartment"),
    ("land", "Land"),
    ("commercial", "Commercial"),
    ("other", "Other"),
]

    TYPE_CHOICES = [
    ("Sell", "For Sale"),
    ("Rent", "For Rent"),
    ("Shortlet", "Shortlet"),
]

    STATUS_CHOICES = [
        ("available", "Available"),
        ("rented", "Rented"),
        ("sold", "Sold"),
]

    # ── Core fields ──────────────────────────────────────────────────────────
    id = models.BigAutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # ── Location ─────────────────────────────────────────────────────────────
    address = models.CharField(max_length=500, unique=True, null=True, blank=True)
    coordinates = models.JSONField(null=True, blank=True)
    # Supabase: {"lat": ..., "lng": ...}  — stored as-is in JSONField

    # ── Owner (FK to user_profiles via email — matches Supabase FK) ───────────
    created_by = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        to_field="email",          # FK was on email column, not id
        db_column="createdBy",     # preserve original column name
        related_name="listings",
    )

    # ── Listing meta ─────────────────────────────────────────────────────────
    active = models.BooleanField(default=False)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="available"
    )

    type = models.CharField(
        max_length=50, choices=TYPE_CHOICES, null=True, blank=True
    )
    property_type = models.CharField(
        max_length=100,
        choices=PROPERTY_TYPE_CHOICES,
        null=True,
        blank=True,
        db_column="propertyType",  # preserve original column name
    )

    # ── Property details ─────────────────────────────────────────────────────
    bedroom = models.CharField(max_length=50, null=True, blank=True)
    bathroom = models.CharField(max_length=50, null=True, blank=True)
    built_in = models.DecimalField(
        max_digits=6, decimal_places=0, null=True, blank=True, db_column="builtIn"
    )
    parking = models.DecimalField(
        max_digits=4, decimal_places=0, null=True, blank=True
    )
    lot_size = models.FloatField(null=True, blank=True, db_column="lotSize")
    area = models.FloatField(null=True, blank=True)

    # ── Financials ───────────────────────────────────────────────────────────
    price = models.FloatField(null=True, blank=True)
    hoa = models.FloatField(null=True, blank=True)
    price_per_night = models.FloatField(null=True, blank=True)
    min_nights = models.PositiveIntegerField(null=True, blank=True)

    # ── Content ──────────────────────────────────────────────────────────────
    description = models.TextField(null=True, blank=True)

    # ── Agent/owner display info ──────────────────────────────────────────────
    profile_image = models.CharField(
        max_length=500, null=True, blank=True, db_column="profileImage"
    )
    full_name = models.CharField(
        max_length=255, null=True, blank=True, db_column="fullName"
    )

    class Meta:
        db_table = "listing"
        ordering = ["-created_at"]
        verbose_name = "Listing"
        verbose_name_plural = "Listings"

    def __str__(self):
        return self.address or f"Listing #{self.id}"


class ListingImage(models.Model):
    """
    Mirrors public.listingimages

    Supabase stored images in a storage bucket; url was the public URL
    and path was the storage object path.
    In Django, you can either keep storing external URLs, or switch to
    ImageField with django-storages (e.g. S3).
    """

    id = models.BigAutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    url = models.CharField(max_length=1000, null=True, blank=True)
    path = models.TextField(null=True, blank=True)
    listing = models.ForeignKey(
        Listing,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="images",
        db_column="listing_id",
    )

    class Meta:
        db_table = "listingimages"
        verbose_name = "Listing Image"
        verbose_name_plural = "Listing Images"

    def __str__(self):
        return f"Image for Listing #{self.listing_id}"

class ListingReport(models.Model):
    """
    A flag raised by a logged-in user against a listing — wrong status,
    suspected fraud, duplicate, etc. Admins review these in
    /control/reports and mark them resolved once handled.
    """

    REASON_CHOICES = [
        ("wrong_status", "Marked as available but isn't"),
        ("fraud", "Suspected fraud or fake listing"),
        ("duplicate", "Duplicate listing"),
        ("inappropriate", "Inappropriate content"),
        ("other", "Other"),
    ]

    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="reports"
    )
    reporter = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="listing_reports",
    )
    reason = models.CharField(max_length=30, choices=REASON_CHOICES)
    details = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    resolved = models.BooleanField(default=False)
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="resolved_reports",
    )

    class Meta:
        db_table = "listing_reports"
        ordering = ["-created_at"]
        verbose_name = "Listing Report"
        verbose_name_plural = "Listing Reports"

    def __str__(self):
        return f"Report #{self.id} on Listing #{self.listing_id} ({self.reason})"

class Favorite(models.Model):
    """
    A logged-in user saving/hearting a listing. One row per (user,
    listing) pair — heart toggles it on/off rather than stacking rows.
    """

    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="favorited_by"
    )
    user = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="favorites"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "listing_favorites"
        unique_together = ("listing", "user")
        ordering = ["-created_at"]
        verbose_name = "Favorite"
        verbose_name_plural = "Favorites"

    def __str__(self):
        return f"{self.user.email} ♥ Listing #{self.listing_id}"


class Inquiry(models.Model):
    """
    A "Contact Agent/Landlord" submission. Open to anonymous visitors
    (name/email/phone captured directly on the form) as well as logged
    -in users (sender is set automatically when authenticated, name/
    email pre-filled from their profile on the frontend).
    """

    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="inquiries"
    )
    sender = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="sent_inquiries",
    )
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=50, blank=True, null=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    class Meta:
        db_table = "listing_inquiries"
        ordering = ["-created_at"]
        verbose_name = "Inquiry"
        verbose_name_plural = "Inquiries"

    def __str__(self):
        return f"Inquiry #{self.id} on Listing #{self.listing_id} from {self.email}"



