# Generated by Django 4.2.30 on 2026-05-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=50, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], db_column='propertyType', max_length=100, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=50, null=True)),
                ('bathroom', models.CharField(blank=True, max_length=50, null=True)),
                ('built_in', models.DecimalField(blank=True, db_column='builtIn', decimal_places=0, max_digits=6, null=True)),
                ('parking', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('lot_size', models.FloatField(blank=True, db_column='lotSize', null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('hoa', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, db_column='profileImage', max_length=500, null=True)),
                ('full_name', models.CharField(blank=True, db_column='fullName', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='accounts.userprofile', to_field='email')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'db_table': 'listingimages',
            },
        ),
    ]
