# Generated by Django 4.2.30 on 2026-08-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family House', 'Single Family House'), ('Town House', 'Town House'), ('Condo', 'Condo'), ('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], db_column='propertyType', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Sell', 'For Sale'), ('Rent', 'For Rent')], max_length=50, null=True),
        ),
    ]
