# Generated by Django 4.2.30 on 2026-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_inquiry_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_night',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Sell', 'For Sale'), ('Rent', 'For Rent'), ('Shortlet', 'Shortlet')], max_length=50, null=True),
        ),
    ]
